name: Ultraviolet-Node
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Runs the specified commands commands to get Ultraviolet-Node running.
      - name: run ultraviolet
        run: |
                  npm install -g localtunnel > /dev/null 2>&1
          tmux new -d -s uv
          sleep 1
          tmux send-keys -t uv "lt -p 8080" ENTER
          sleep 1
          tmux capture-pane -pt uv -S 1 -E 1
          git clone https://github.com/IDontCodee/Tsunami --recursive
          cd Tsunami
          npm install
          npm start
          screen -dm npm start
